apiVersion: v1
kind: Service
metadata:
  name: htbe-service
spec:
  selector:
    app: htbe-depl
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080 # needs to match the container port from the deployment config file