# Yaml allows also for 2 Files in 1 File by seperating via "---":
#DeploymentFile
#---
#ServiceFile
#CONFIG MAP MUST EXIST IN CLUSTER BEFORE WE CAN EXECUTE THIS, SO FIRST EXECUTE MONGO_CONGIGMAP.YAML!
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mongo-express
  name: mongo-express
spec: # deployment-spec
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  strategy: {}
  template:
    metadata:
      labels:
        app: mongo-express
    spec: #  pod-spec
      containers:
        - image: mongo-express
          name: mongo-express
          ports:
            - containerPort: 80
          env:
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongo-root-username
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongo-root-password
            - name: ME_CONFIG_MONGODB_SERVER
              valueFrom:
                configMapKeyRef:
                  name: mongo-express-configmap
                  key: database_url
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-express-service
spec:
  selector:
    app: mongo-express
  type: LoadBalancer #accepts external requests by assigning the service an external IP
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 80
      nodePort: 30002 #Port where external IP address will be open (needs to be between 30000 and 32767)