#usually you wouldnt put the secret in the same file but in this demo case its whatever
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
data:
  mongo-root-username: dXNlcm5hbWU=
  # these values need to be entered base 64 encoded. Here i want my username to be "username" so
  #in the terminal ill write: powershell "[convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes(\"username\"))"
  mongo-root-password: cGFzc3dvcmQ=
  # or you can look online for a base 64 encoder.. our password will be "password"